### ISSUE TITLE
Finish function "get_day_point()"

### ISSUE THREAD

**Issue by waittim** [dsi-principles-prog/midterm-waittim#2]
Create a function for splitting the trending date column into 3 columns. The date of trending might be used to analyze how long it takes after posting the video and it could be an interesting difference.

The created column should be 3 numerical columns.

**assert sentences:**
assert(data = USvideos_NNA, in_set(2017, 2018, allow.na = FALSE), date_year)
assert(data = USvideos_NNA, in_set(seq(1,12,1), allow.na = FALSE), date_month)
assert(data = USvideos_NNA, in_set(seq(1,31,1), allow.na = FALSE), date_day)

Hint: if you feel it's a little bit difficult, maybe look at the *get_time_point()* is a good idea.

**Comment by yasiwang0315** [comment]
added year, month, day feature, closes #2
